import Head from 'next/head'

export default function Post<Any>() {
    return (
        <>
            <Head>
                <title>Title</title>
                <meta name={'description'} content={'Generated by create next app'} />
            </Head>
            <header>

            </header>
        </>
    )
}