import type { NextPage } from 'next'
import Head from 'next/head'

const About: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Rafael Alves</title>
                <meta name='description' content='Generated by create next app' />
            </Head>
        </div>
    )
}

export default About