import type { NextPage } from 'next'
import NavBar from '../components/NavBar'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Homer: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Rafael Alves</title>
                <meta name='description' content='Generated by create next app' />
            </Head>
            <header className={styles.header}>
                <NavBar />
            </header>
            <main className={styles.main}>
                <h1 className={styles.title}>Blog</h1>
            </main>
            <footer>

            </footer>
        </div>
    )
}

export default Homer