import type { NextPage } from 'next'
import Head from 'next/head'
import Card from '../components/Card'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import { getSortedPostsData } from '../lib/getPosts'

export const getStaticProps: GetStaticProps = async () => {
    const allPostsData = getSortedPostsData()

    return {
        props: {
            allPostsData
        }
    }
}


const Home: NextPage = ({ allPostsData }: InferGetStaticPropsType<typeof getStaticProps>) => {
    return (
        <>
            
            <Head>
                <title>Rafael Alves</title>
                <meta name='description' content='Generated by create next app' />
            </Head>

            <style jsx>{`

                h1 {
                    font-size: 3em;
                    text-align: center;
                }

                h1 > mark {
                    background: linear-gradient(120deg, #ff0000 0%, #ff0000 100%);
                    background-repeat: no-repeat;
                    background-size: 100% 35%;
                    background-position: 0 90%;
                }

                .card-section {
                    display: flex;
                    flex-flow: row wrap;
                    justify-content: center;
                    width: 100%;
                    gap: 2em;
                }
            
            `}</style>

            <h1>My thoughts on <mark>Technology</mark></h1>

            <section className={'card-section'}>
                {allPostsData.map(({slug, date, title}) => (
                    <Card key={slug} slug={slug} title={title} date={date} />
                ))}
            </section>

        </>
    )
}

export default Home