import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Date from '../components/date'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import { getSortedPostsData } from '../lib/getPosts'

export const getStaticProps: GetStaticProps = async () => {
    const allPostsData = getSortedPostsData()

    return {
        props: {
            allPostsData
        }
    }
}


const Home: NextPage = ({ allPostsData }: InferGetStaticPropsType<typeof getStaticProps>) => {
    return (
        < >
            
            <Head>
                <title>Rafael Alves</title>
                <meta name='description' content='Generated by create next app' />
            </Head>

            <h1 >Blog</h1>
            <ul>
                {allPostsData.map(({slug, date, title}) => (
                    <li key={slug} >
                        <Link href={`/posts/${slug}`} >
                        <a>{title}</a>
                        </Link>
                        <br/>
                        {slug}
                        <br/>
                        <Date dateString={date} />
                    </li>
                ))}
            </ul>

        </>
    )
}

export default Home