import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Date from '../components/Date'
import Card from '../components/Card'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import { getSortedPostsData } from '../lib/getPosts'

export const getStaticProps: GetStaticProps = async () => {
    const allPostsData = getSortedPostsData()

    return {
        props: {
            allPostsData
        }
    }
}


const Home: NextPage = ({ allPostsData }: InferGetStaticPropsType<typeof getStaticProps>) => {
    return (
        <>
            
            <Head>
                <title>Rafael Alves</title>
                <meta name='description' content='Generated by create next app' />
            </Head>

            <style jsx>{`
                .card-section {
                    display: flex;
                    flex-flow: row wrap;
                    justify-content: center;
                    width: 100%;
                }
            `}</style>


            <section className={'card-section'}>
                {allPostsData.map(({slug, date, title}) => (
                    <Card key={slug} slug={slug} title={title} date={date} />
                ))}
            </section>

        </>
    )
}

export default Home